### ISSUE TITLE
Adicionar loading em todos os botões

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#14]
Quando eu clico em entrar ele não me traz nenhuma resposta:

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/204c8f4b-975b-41f1-ba2f-216496031a04)

É extremamente importante informar o usuário de tudo que está acontecendo, então adicione alguma informação de loading no botão, ou trocar o texto para carrendo ou uma animação

**Comment by JhonesJhonatas** [comment]
Feature adicionada, atualização será hoje (01/11) por volta das 20h
