### ISSUE TITLE
Label e input de data 

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#18]
colocar em português a label e não apareceu calendário para clicar na data, é um comportamento esperado de input de data 

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/e93af037-a1ae-44d6-a9fe-2a906b9e8ba7)

**Comment by JhonesJhonatas** [comment]
Os campos de seleção no modal agora são autoexplicativos e não possuem labels, o campo de seleção de data pode ser usado tanto para obter uma data digitada, ou abrindo um calendario  quando clicado no ícone.
