### ISSUE TITLE
Não retornou mensagem de error

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#19]
ao tentar criar uma task flatando informações ele não mostrou erro ao usuário

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/f06e1d62-99d6-4d20-8f96-55739ba9d943)

**Comment by JhonesJhonatas** [comment]
Foram adicionadas notificações para avisar ao usuário sempre que ocorrer algum erro ou incossistência de dados.
