### ISSUE TITLE
Adicionar "*" ou "(Obrigatório)" no inputs

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#20]
Não tem como o usuário saber se o input é obrigadtório antesde clicar em criar, e mesmo assim ele deveria mudar a cor da borda para ficar mais visual e tem alguma informação extra "*" ou "(Obrigatório)"

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/5a076c88-994c-411a-9d37-8f97ee852561)

exemplos:
![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/93a532d4-a056-4aac-9296-21ae3c8d13c4)
![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/6f881b2a-1f37-42ef-87dd-c110944b89f6)

**Comment by JhonesJhonatas** [comment]
Apenas dois campos são obrigatórios na criação da task agora, foram adicionadas notificações para avisar quando eles não forem preenchidos.
