### ISSUE TITLE
Não vejo sentido ter q vincular obrigatoriamente um projeto a uma task

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#21]
Eu poderia querer usar sua aplicação apenas para tarefas do dia a dia, uma task lavar louça, porque necessitaria de um projeto pra isso?

Eu não sabia que era obrigatório ter um projeto para poder crirar uma task tem que melhorar isso 

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/b85df684-10a4-47c8-a4bd-c7c0c0b472b2)

**Comment by JhonesJhonatas** [comment]
Olá @lEduFranco , nesse caso aconselho que crie um projeto com o título "Pessoal" ou algo semelhante, a ideia das tarefas serem sempre atreladas a um projeto é para permitir emissão de relatórios sobre o projeto no futuro.

Quanto a questão de deixar claro que é obrigatório, isso vai ser melhorado durante a alteração completa desse modal.

Vou manter a issue aberta até que o modal seja refeito ;D

**Comment by JhonesJhonatas** [comment]
Modal completamente reestruturado na versão atual e agora um projeto Geral é criado junto com a criação de um usuário.
