### ISSUE TITLE
Resetar formulário do modal

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#22]
Ao clicar no "X" ou em "Cancelar" do modal ele não resetou as informações inseridas antes no formulário

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/581dc152-9c7e-48b5-9909-39a14a7b91c2)

[Vídeo do bug](https://app.usebubbles.com/bvVjP4aHvNcGN4eGUCW1Jk)

**Comment by JhonesJhonatas** [comment]
Resolvido
