### ISSUE TITLE
Tarefa já concluída aparecendo botão de concluir

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#24]
![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/d39547ba-b9f2-4f08-9a63-b0aa62561815)

**Comment by JhonesJhonatas** [comment]
Resolvido.
Atualmente, em tasks concluídas todos os inputs ficam desabilitados e aparece um botão para desfazer a conclusão da tarefa, torando ela editável novamente.
