### ISSUE TITLE
Botão de concluir ficou muito confuso, não existe esse padrão nos outros sistemas de tasks

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#25]
esse concluir parece que é pra salvar a alteração e não para concluir a tarefa toda

eu removeria ele pois já tem no select ou melhoraria essa posição ou a forma como está colocado em tela

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/a5d04d73-d78c-43c3-9734-d0927300a287)

**Comment by JhonesJhonatas** [comment]
Modal de task foi completamente reconstruído na versão atual ;D
