### ISSUE TITLE
Adicionar a possibilidade de trocar o status da task sem ter q abrir o modal 

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#26]
exmplo: 

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/e24f850e-bb01-40fa-af30-dc2c2c3a2bd8)

**Comment by JhonesJhonatas** [comment]
Feature inserida na atualização do dia 12 de Fevereiro ;D
