### ISSUE TITLE
O tempo limite de uma task não pode ser menor que a data atual

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#27]
![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/ae128285-90da-4d52-8bdc-f5bcce276765)

**Comment by JhonesJhonatas** [comment]
No futuro, o sistema terá uma página de relatórios que mostrará dados mensais de cada projeto, é possível inserir um deadline com uma data no passado para que o usuário possa registar informações esquecidas, se for o caso, com a data correta em que foi realizada.
