### ISSUE TITLE
Contador das concluídas não funciona 

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#32]
![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/f92b5565-8f0c-4105-a06c-255b393a9e13)

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/1f373567-ddf9-41ec-9744-50e0d9b3fc76)

**Comment by JhonesJhonatas** [comment]
Resolved
