### ISSUE TITLE
Erro no redirecionamento

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#33]
Se eu editar uma task aberta pelo dashboard ele está redirecionando para a tela de todas as tarefas, deveria apenas fechar o modal

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/55c876d0-885a-4346-8187-ee2f422e3a21)

[Vídeo do bug](https://app.usebubbles.com/sRwmY8VpTxaNqutsFmo3o7)

**Comment by JhonesJhonatas** [comment]
Resolved
