### ISSUE TITLE
Tarefa atrasada não aparece no dashboard

### ISSUE THREAD

**Issue by lEduFranco** [JhonesJhonatas/dont-forget-web#34]
![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/20f0ab18-259f-4e2c-bdea-a5bb0a8017af)

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/60003877/518bdaba-da77-4d89-9537-3de5e468a2a6)

**Comment by JhonesJhonatas** [comment]
Bug resolvido
