### ISSUE TITLE
404: NOT_FOUND

### ISSUE THREAD

**Issue by Joao-Bittencourt** [JhonesJhonatas/dont-forget-web#60]
Ao entrar na tela de https://www.dontforget.com.br/dashboard, e recarregar a pagina está dando este erro :

![image](https://github.com/JhonesJhonatas/dont-forget-web/assets/24395717/447493c1-18bf-479b-8bee-89c601140296)

**Comment by JhonesJhonatas** [comment]
Show, corrigido. Muito obrigado pela contribuição! ;D
